### ISSUE TITLE
GSR does not send DELETE message during the shutdown

### ISSUE THREAD

**Issue by szigetigabor** [eu-emi/emiregistry#61]
ERROR wsrflite  -  Error during the delete message sending 
 ERROR wsrflite  - The root error was: java.lang.ClassCastException: java.lang.String cannot be cast to org.codehaus.jettison.json.JSONObject
2012-07-20 11:35:04,116 [Thread-13] DEBUG wsrflite  - Stack trace
java.lang.ClassCastException: java.lang.String cannot be cast to org.codehaus.jettison.json.JSONObject
    at eu.emi.emir.p2p.ServiceEventReceiver.recieve(ServiceEventReceiver.java:78)
    at eu.emi.emir.p2p.GSRHelper.stopGSRFunctions(GSRHelper.java:77)
    at eu.emi.emir.EMIRServer$1.run(EMIRServer.java:91)

**Comment by szigetigabor** [comment]
Done
https://github.com/eu-emi/emiregistry/commit/a74c7236bacd7f7ad1b8389feb0e7959164d8ecc
