### ISSUE TITLE
NPE when GSR is solo

### ISSUE THREAD

**Issue by amemon** [eu-emi/emiregistry#83]
The GSR throws Null Exception in startup.log when there is only one GSR

Exception in thread "emir-executor-6" java.lang.NullPointerException
        at eu.emi.emir.p2p.NeighborsManager.GetInfoProvidersFromConfiguration(NeighborsManager.java:646)
        at eu.emi.emir.p2p.NeighborsManager.<init>(NeighborsManager.java:81)
        at eu.emi.emir.p2p.NeighborsManager.getInstance(NeighborsManager.java:129)
        at eu.emi.emir.p2p.NeighborsEventReciever.recieve(NeighborsEventReciever.java:78)
        at eu.emi.emir.event.EventDispatcher$1.run(EventDispatcher.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)

**Comment by szigetigabor** [comment]
How can I reproduce it?
What are you set in the configuration?

**Comment by amemon** [comment]
enable the global flag, set the address starting from http, and then start.

**Comment by szigetigabor** [comment]
The provider list was not configured.
Fixed it: https://github.com/eu-emi/emiregistry/commit/a66d524b742d7df8726cc222a9e1202b7bc8d7ad
